

    <nav class="text-center">
        <a href="/" class="btn btn-dark mx-1 mb-2 mt-2">
            <i class="fa-solid fa-home"></i>
            Accueil
        </a>

        <a href="/annonces/add" class="btn btn-dark mx-1">
            <i class="fa-solid fa-plus"></i>
            Ajouter un produit
        </a>

        <a href="/annonces/all" class="btn btn-dark mx-1">
            <i class="fas fa-list"></i>
            Consulter tous les produits
        </a>

     

    </nav>